package com.todolist.demo.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * This class indicates the object Todo, with JPA bounded to the DB.
 * For this class are needed to add the Starters: [Spring Data JPA, MySql Driver]
 * Entity: The generation type lets the database generate a new value with each insert operation
 * Id and GeneratedValue: The parameter that will be a unique id autogenerated by the db
 * @version 0.0.1
 * @author Carlo Tacchella
 * @since 22/09/07
 */

@Entity
public class Todo {
	/**
	 * The generation type lets the database generate a new value with each insert operation
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private String title;
	private String subtitle;
	
	public Todo() {
		
	}
	
	public Todo(int id, String title, String subtitle) {
		this.id = id;
		this.setTitle(title);
		this.setSubtitle(subtitle);
	}
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubtitle() {
		return subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}
}
