package com.todolist.demo.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * This class indicates the object Todo, with JPA bounded to the DB.
 * For this class are needed to add the Starters: [Spring Data JPA, MySql Driver]
 * Entity: The generation type lets the database generate a new value with each insert operation
 * Id and GeneratedValue: The parameter that will be a unique id autogenerated by the db
 * @version 0.0.1
 * @author Carlo Tacchella
 * @since 22/09/07
 */

@Entity
public class Todo {
	/**
	 * The generation type lets the database generate a new value with each insert operation
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private String url;
	
	public Todo() {
		
	}
	
	public Todo(int id, String url) {
		this.id = id;
		this.url = url;
	}
	
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	public String getUrl() {
		return url;
	}
	
	public void setUrl(String url) {
		this.url = url;
	}
}
